### PR TITLE
fixed library headers and reformatted

### PR DESCRIPTION
**Pull request by scruss**
Somehow, the licence file had got into the library files without triple-quotes, so all code would fail with errors such as:

    Traceback (most recent call last):
      File "<stdin>", line 9, in <module>
      File "/lib/hx711_pio.py", line 1
    SyntaxError: invalid syntax

also removed old files that were left over from original repo

### CODE REVIEW

**Comment by robert-hh** [comment]
Thanks. It's like that since November last year, and no one complained. I pushed new files with the license header as comment.

**Comment by scruss** [comment]
Thanks! It works really well!

There's a debugging print still in the pio version, see
https://github.com/robert-hh/hx711/blob/5c6e5b75c41f4fcbb6e8278ba3abf21c7a9c9dec/hx711_pio.py#L99

**Comment by robert-hh** [comment]
I'll remove that.
About the post that you reported just now in the old forum: Thanks for seeing that. It is a bad trick. I had approved that this morning. It was suspicious, since it responded to an old topic, but that happens, and it had no additional link or the like. Just the text. So after getting approval, the poster must have added that link.

**Comment by scruss** [comment]
I've seen spammers do that before on other phpBB sites. Another reason to make it completely read-only, I guess. Thanks for the moderation! It's a thankless task

**Pull request closed without merging**
